server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hobby-sync
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: validate
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: false
        format_sql: false
  flyway:
    placeholder-replacement: false
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
openai:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo